### ISSUE TITLE
Problemy przy pierwszym uruchomieniu

### ISSUE THREAD

**Issue by michalzadkowski** [tcich/ha-addon-energa-meter#1]
Nie wiem jaki jest dokładnie mój problem, addon nie pobiera danych i tyle. Loguje się do Mój licznik i dalej już dramat.

Fragment loga:

```[09:52:54] INFO: Uruchamiam API
[09:52:54] INFO: Uruchamiam MAIN
Traceback (most recent call last):
  File "//main.py", line 35, in <module>
Inicjacja...
Logowanie... login@email.com
Logowanie rozpoczęte.
Zalogowano
Licznik 1234567890 nie istnieje w systemie.
Aktualizacja liczników...
Zapisano stan licznika 1234567 na dzień: 2023-09-20
Wyszukiwanie najstarszych danych...
Szukam najstarsze dane historyczne licznika 1234567
    main()
  File "//main.py", line 27, in main
    mojLicznik.update_first_date()
  File "/moj_licznik.py", line 224, in update_first_date
    first_day_of_month = datetime(last_chart_year, n, 1)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object cannot be interpreted as an integer
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by tcich** [comment]
Poproszę o informację jaka taryfa i jest to licznik odbiorcy czy też wytwórcy energii?

**Comment by tcich** [comment]
Aplikacja Mój licznik była wyłączona w celach serwisowych, została uruchomiona. Proszę o zweryfikowanie czy obecnie addon działa prawidłowo.

**Comment by michalzadkowski** [comment]
Dzięki za informacje - póki co wstrzymam się jeszcze, bo okazuje się że z moim kontem są jakieś problemy. Dane się nie zbierają, mam tylko odczyt i to sprzed miesiąca. Zgłosiłem to Enerdze i w ciągu 2 tygodni mają coś zaradzić.
Jeśli sytuacja się poprawi i okaże się, że problem był po stronie Energi, zamknę issue i nie będę zawracał głowy.

**Comment by kmieeciu** [comment]
Witam, w logach mam taki błąd: Template variable error: 'dict object' has no attribute 'countner' when rendering '{{ value_json.countner.meter_value | round(2) }}'

**Comment by tcich** [comment]
> Dzięki za informacje - póki co wstrzymam się jeszcze, bo okazuje się że z moim kontem są jakieś problemy. Dane się nie zbierają, mam tylko odczyt i to sprzed miesiąca. Zgłosiłem to Enerdze i w ciągu 2 tygodni mają coś zaradzić.
> Jeśli sytuacja się poprawi i okaże się, że problem był po stronie Energi, zamknę issue i nie będę zawracał głowy.

Zamykam
