### ISSUE TITLE
Nie można zainstalować dodatku

### ISSUE THREAD

**Issue by Pramerica7** [tcich/ha-addon-energa-meter#10]
Podczas instalacji dodatku pojawia się błąd:

![image](https://github.com/user-attachments/assets/83c02d14-2710-4cc7-883e-f7187951b35b)

**Comment by paki111** [comment]
Próbowałeś ponownie? Ja zainstalowałem 3 dni temu bez problemu.

**Comment by Pramerica7** [comment]
Tak, ciągle wyskakuje ten sam komunikat

**Comment by tcich** [comment]
błąd nie występuje, nie można go zreplikować, proszę o przesłanie więcej szczegółów

**Comment by Pramerica7** [comment]
Spróbowałem jeszcze raz, repozytorium dodane jeszcze raz, ten sam błąd przy próbie instalacji.
![enrgm1](https://github.com/user-attachments/assets/d5b9ac7b-01fe-4739-8753-9573ae56e9e3)
