### ISSUE TITLE
pobieranie zużycia z kilku dni po czasowym braku komunikacji z licznikiem

### ISSUE THREAD

**Issue by paki111** [tcich/ha-addon-energa-meter#11]
Cześć @tcich! Super, że zrobiłeś prawdziwą integrację z portalem a nie tylko scraping (bo na takie 2 dodatki wcześniej trafiłem). Jestem mega zadowolony, że trafiłem na ten dodatek. Świetna robota!

Zdarza się, że licznik nie ma kontaktu z siecią GPRS np. kilka dni. Ja używam integracji do odczytywania sześciu liczników w moim bloku. Liczniki są w piwnicy gdzie jest słaby zasięg. Po odzyskaniu komunikacji, system zdalnego odczytu Energi pobiera brakujące odczyty zbuforowane na liczniku. Odczyty mają datę i czas, dlatego nie ma problemu na portalu mojlicznik, bo tam uwzględniana jest data i godzina każdego odczytu. Czasami trzeba poczekać kilka dni, ale finalnie jest wszystko cacy.

Problem pojawia się niestety w HA, gdyż całe zużycie zbuforowane np. z dwóch-trzech dni zapisywana jest z datą pobrania danych z serwera. To jest szczególnie istotne przy analizie odczytów dziennych. Im dłuższy okres analizy tym problem mniejszy.

![problem z odczytami dziennymi](https://github.com/user-attachments/assets/8fbb7e84-43bb-487d-8d31-0687964492ba)

Czy dałoby się pobierać z portalu mojlicznik również datę i czas poszczególnych odczytów a nie tylko przyrost zużycia od ostatniego pobrania danych?

**Comment by paki111** [comment]
wiem, że się nie da - nie ma kontroli nad datą wprowadzania odczytów do bazy HA

**Comment by paki111** [comment]
wiem, że się nie da - nie ma kontroli nad datą wprowadzania odczytów do bazy HA

**Comment by tcich** [comment]
https://github.com/tcich/ha-addon-energa-meter/blob/main/src/README.md

API dla wykresów, np. Grafana
Instrukcja pełna https://github.com/tcich/ha-addon-energa-meter/blob/main/src/INSTALL.md
