### ISSUE TITLE
Błędne wczytywanie danych za dzień poprzedni

### ISSUE THREAD

**Issue by McKasta** [tcich/ha-addon-energa-meter#13]
Witam 
Mam problem z błędnie wczytywanymi danymi z dnia poprzedniego.
Nowe wartości licznika pokazują się po północy więc HA zalicza je już do obecnej doby.
O godzinie 0:10 mam zużycie z całego dnia poprzedniego a dzisiejsze dane wczytają się jutro o tej samej porze.
Czy jest możliwość przesunąć te dane w czasie by HA poprawnie rozdzielał doby?

**Comment by paki111** [comment]
Też mi się to nie podoba, aczkolwiek nie nazywał bym tego błędem. Po północy aktualizują się stany liczydeł w systemie zdalnego odczytu. HA zapisuje stan w dacie i godzinie jego odczytania. Nie można zapisywać odczytów w wybranej przez siebie dacie i godzinie. 
Ja widzę dwa rozwiązania, z których pierwsze można zastosować samodzielnie: 
1. Operacja na bazie danych. Update kolumny z datą w tabeli statystyk. 
2. Modyfikacja dodatku Energa Meter. Przejście z odczytywania stanu liczydła (które aktualizuje raz dziennie po północy) na odczyty godzinowe, które widać w zakładce 'Wykres'.

**Comment by tcich** [comment]
dane pojawiają się wtedy kiedy zostaną udostępnione, nie ma możliwości dodawania ich z datą wsteczną
