### ISSUE TITLE
Odczyt za często, wystarczy raz skuteczny na dobę 

### ISSUE THREAD

**Issue by kzajac83** [tcich/ha-addon-energa-meter#15]
Witam.

Zgodnie z FAQ Energi i punktem 23. dane odświeżane są raz dzienne, co zresztą widać na pobieranych danych.

https://mojlicznik.energa-operator.pl/dp/MainFaq.do

> 23. Jak często dane z licznika są przesyłane do Portalu Mój Licznik?
> System technologiczny gromadzi dane z liczników na bieżąco. Jednak z uwagi na złożoność procesu pozyskiwania danych i wykonania niezbędnych obliczeń na Portalu Mój Licznik udostępnianie są dane dla zakończonej doby.

W związku z tym po co dodatek odpytuje co 10 min portal Mój Licznik generując jałowy ruch i sztuczne obciążenie (małe, ale zawsze)? Czy nie lepiej sprawdzać aktualny timestamp i np. 10 min po północy starać się do skutku pobrać dane jednorazowo z portalu Mój Licznik?  

Pozdrawiam, Krzysiek

**Comment by paki111** [comment]
Na zakładce licznik mamy dane raz na dobę, ale na zakładce wykres mamy odczyty godzinowe. Mam nadzieję, że kiedyś ten dodatek (lub inna integracja) będzie w stanie pobierać te dane godzinowe.

**Comment by kzajac83** [comment]
Rozumiem, jest jak piszesz.

Niemniej update co np. 12h, a nie 20 min myślę, że warto zmienić, skoro i tak dane z wykresów nie są obecnie dostępne

**Comment by paki111** [comment]
Mam kilkanaście liczników podpiętych na koncie i niestety zdarza się, że nie wszystkie są aktualizowane po północy. Niektóre po kilku godzinach. Poniżej przykład.
![image](https://github.com/user-attachments/assets/17de4cef-c89d-4403-b54c-f4c0550013b9)

**Comment by tcich** [comment]
dane udostępnianie są co kilkadziesiąt minut, stan licznika jest aktualizowany nie wcześniej niż o północy, jednak nie jest określone kiedy

**Comment by tcich** [comment]
dane godzinowe są pobierane cyklicznie, można je sobie oglądać za pomocą np. grafana

**Comment by kzajac83** [comment]
@tcich jestem nowym userem rozwiązania, ale u mnie nie ma żadnego update od moment pobrania pierwszych danych po północy, jak Ty pobierasz dane godzinowe?

![image](https://github.com/user-attachments/assets/7ce44214-17e1-4527-9a1c-9190997ea842)

**Comment by tcich** [comment]
https://github.com/tcich/ha-addon-energa-meter/blob/main/src/README.md

API dla wykresów, np. Grafana 
Instrukcja pełna https://github.com/tcich/ha-addon-energa-meter/blob/main/src/INSTALL.md

**Comment by paki111** [comment]
> dane godzinowe są pobierane cyklicznie, można je sobie oglądać za pomocą np. grafana

Dzięki za przypomnienie, teraz widzę. Pod adresem http://adres_IP_twojego_HA:8000/charts/ jednak są dane godzinowe. Jak sprawdzałem wcześniej to albo nie miałem tego jsona albo nie zauważyłem, że to są dane godzinowe.

Zrobiłem sobie pierwszy dashboard w Grafana (mam kilka liczników).

![image](https://github.com/user-attachments/assets/1c8a4465-f7ff-497d-b38d-66e9da580ab1)

**Comment by kzajac83** [comment]
Da się tymi danymi godzinowymi aktualizować główne albo jakieś dwie nowe encje?  Tj na pewno się jakoś da natomiast jak to zrobić?   


Też coś było nie tak z instrukcją, najgorsze to źle sformatowany tekst, który w moim przypadku wklejał się transponowany tj każda literka oddzielnie i enter, tak że napis był pionowo wklejony, a nie normlanie jednej za drugim. 



Ale jestem pod wrażeniem, na szybkości zajrzałem i jest masa danych historycznych.  Tym bardziej chciałbym je jakoś ściągnąć do HA, a nie trzymać w Grafanie. Pytanie jak?

Dane są trzymane jeden rok:
![image](https://github.com/user-attachments/assets/2cfac048-aa84-45be-9f79-e2f51cfe56ed)

**Comment by paki111** [comment]
Te dane pochodzą bezpośrednio z platformy mojlicznik, nie zapisują się w bazie HA. Okres może być dłuższy, to zależy od kiedy masz zdalny odczyt zamontowany, ja widzę kilka lat wstecz.

**Comment by kzajac83** [comment]
Ja to rozumiem, natomiast jak przetransferować dane godzinowe z serwera Energi do HA?

Ja mam równo dwa lata dostępne. Może dlatego, że jest PV i być może dla niej trzymają minimum jeden rok, a drugi w razie W ponieważ rozliczenie energii wyprodukowanej jest do roku czasu wstecz.  Przynajmniej nie mogę cofnąć się dalej w czasie niż dokładnie do 6.11.2023 i bieżącej godziny. 

![image](https://github.com/user-attachments/assets/d601dbe2-39b6-4f47-9b67-1afe721c25a4)
