### ISSUE TITLE
Liczniki A-

### ISSUE THREAD

**Issue by jojoro1** [tcich/ha-addon-energa-meter#3]
Dodałem liczniki A+ zgodnie z instrukcją:
```
- platform: rest
    resource: http://localhost:8000/123456789/A%2B/1
    name: "A+ Taryfa 1"
    unique_id: 123456789_apt1
    unit_of_measurement: "kWh"
    value_template: "{{ value_json.countner.meter_value | round(2) }}"   
  - platform: rest
    resource: http://localhost:8000/123456789/A%2B/2
    name: "A+ Taryfa 2"
    unique_id: 123456789_apt2
    unit_of_measurement: "kWh"
    value_template: "{{ value_json.countner.meter_value | round(2) }}"      
``` 
Wszystko działa.
Jak dodać liczniki A- ?

Czy jest możliwość wykorzystania tej integracji do stworzenia klasy "energy" do użycia w panelu "Energia"?

**Comment by tomek7b6** [comment]
- platform: rest
    resource: http://localhost:8000/123456789/A-/1
    name: "A- Taryfa 1"
    unique_id: 123456789_aot1
    unit_of_measurement: "kWh"
    value_template: "{{ value_json.countner.meter_value | round(2) }}"

**Comment by tcich** [comment]
platform: rest
resource: http://localhost:8000/123456789/A-/1
name: "A- Taryfa 1"
unique_id: 123456789_aot1
unit_of_measurement: "kWh"
value_template: "{{ value_json.countner.meter_value | round(2) }}"

niestety do energia nie można wgrać historii, ale nie wykluczam w nowych wersjach takiej funkcji
